exclude: "^^nvidia_variant_provider/vendor|^.devcontainer/|nvidia_variant_provider/pynvml.*"

default_language_version:
  python: python3.14

# ========================================================================= #
#                                 FORMATING                                 #
# ========================================================================= #

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/artifacts/
      - id: end-of-file-fixer
        exclude: ^tests/artifacts/
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^tests/artifacts/
      # Formatter
      - id: ruff-format
        exclude: ^tests/artifacts/

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1 # check for the latest version
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
          ]
        additional_dependencies: ["autoflake"]

  # ========================================================================= #
  #                           DEPENDENCY MANAGEMENT                           #
  # ========================================================================= #

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.24
    hooks:
      - id: uv-lock
        args: ["--check"]

  # ========================================================================= #
  #                            LICENSING MANAGEMENT                           #
  # ========================================================================= #

  - repo: local
    hooks:
      - id: check-spdx
        name: Check SPDX Headers
        entry: python ./toolshed/check_spdx.py
        language: python
        additional_dependencies:
          - https://files.pythonhosted.org/packages/cc/20/ff623b09d963f88bfde16306a54e12ee5ea43e9b597108672ff3a408aad6/pathspec-0.12.1-py3-none-any.whl

  # ========================================================================= #
  #                                 SECURITY                                  #
  # ========================================================================= #

  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-iii", "-ll"]

  - repo: https://github.com/pysentry/pysentry-pre-commit
    rev: v0.3.11
    hooks:
      - id: pysentry
        args:
          [
            "--format=human",
            "--all-extras",
            "--fail-on=medium",
            "--sources=pypa,osv,pypi",
            "--ignore=GHSA-4xh5-x5gv-qwph"
          ]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
