[build-system]
requires = [ "setuptools>=61.0", "wheel" ]
build-backend = "setuptools.build_meta"


[project]
name = "nvidia-variant-provider"
version = "1.0.0"
description = "A Variant Provider Plugin for the `nvidia` namespace"
dependencies = [ "variantlib" ]


[project.entry-points."variantlib.plugins"]
nvidia_variant_provider = "nvidia_variant_provider.plugin:NvidiaVariantPlugin"
